name: beanstalk
description: "A social app for cafe lovers."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  geolocator: ^14.0.2
  go_router: ^17.0.0
  google_maps_flutter: ^2.14.0
  http: ^1.6.0
  image_picker: ^1.2.1
  json_annotation: ^4.9.0
  json_serializable: ^6.11.3
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.4

flutter:
  uses-material-design: true
